/* Bilingual CV content. Read by resume.js, resume-graphs.js and the PDF generator.
   Edit content here, not in resume.html. */

window.CV_DATA = {
  meta: {
    name: 'Jose Luis Gómez Marín',
    handle: 'jose.gomez',
    os_name: 'JOSE_OS',
    os_version: 'v2.0.0',
    role: {
      es: 'DevOps · SRE · Tech Lead',
      en: 'DevOps · SRE · Tech Lead',
    },
    tagline: {
      es: '> SUBJECT.profile.load()',
      en: '> SUBJECT.profile.load()',
    },
    email: 'jose.gnu@gmail.com',
    location: 'Cantabria, Spain',
    remote: true,
    b2b: true,
    linkedin: 'https://www.linkedin.com/in/jose-luis-gomez-marin/',
    github: 'https://github.com/j-hashed-gomez',
    status: {
      es: 'DISPONIBLE para liderazgo senior · DevOps / SRE / Tech Lead',
      en: 'AVAILABLE for senior leadership · DevOps / SRE / Tech Lead',
    },
  },

  languages: [
    { code: 'es', name: { es: 'Español', en: 'Spanish' }, level: { es: 'Nativo', en: 'Native' },         percent: 100 },
    { code: 'en', name: { es: 'Inglés',  en: 'English'  }, level: { es: 'C1 Avanzado', en: 'C1 Advanced' }, percent: 80  },
  ],

  about: {
    es: [
      'Fascinado por la informática desde que mis padres me regalaron un Sinclair Spectrum 128k en 1986, cuando los dinosaurios aún caminaban sobre la tierra. Desde ese maravilloso día, hasta hoy, 40 años después, no recuerdo un solo día en que no haya aprendido algo nuevo, encontrado algo emocionante en lo que me gustara profundizar.',
      'Creo que estoy en un punto dulce de mi carrera profesional. Con más de 20 años de experiencia, he tenido la oportunidad de aprender este negocio desde los fundamentos, creciendo paso a paso, sin apresurarme, saboreando cada nuevo trabajo, cada nuevo rol.',
      'Ahora puedo ofrecerme como un profesional de TI de alto nivel con una sólida experiencia en temas clave: Liderazgo de equipos, Servicios en la Nube, Redes y Administración de Sistemas. Enfocado en los resultados, compromiso a largo plazo y cultura de equipo en el ADN.',
    ],
    en: [
      "Fascinated by computing since my parents gave me a Sinclair Spectrum 128k in 1986, when dinosaurs still walked the earth. From that wonderful day, until today, 40 years later, I can't remember a single day I haven't learned something new, found something exciting I liked to dig into.",
      "I think I'm in a sweet spot of my professional career. With more than 20 years of experience, I've had the opportunity to learn this business from the ground up, growing step by step, not rushing, savoring every new job, every new role.",
      'Now I can offer myself as a top IT professional with a solid background in key subjects: Team Leading, Cloud Services, Networking and System Administration. Results focused, long term commitment and Team Culture in DNA.',
    ],
  },

  experience: [
    {
      id: 'cloudblue_2026',
      start: '2026-03', end: null,
      title:   { es: 'Senior DevOps Engineer',     en: 'Senior DevOps Engineer'     },
      company: 'CloudBlue (a HostPapa Company)',
      period:  { es: 'Marzo 2026 — Presente',      en: 'March 2026 — Present'       },
      description: {
        es: 'Gestionando y evolucionando un gran ecosistema para llevar la plataforma al siguiente nivel.',
        en: 'Managing and evolving a large ecosystem to take the platform to the next level.',
      },
      bullets: { es: [], en: [] },
      stack: ['Azure', 'GCP', 'Virtuozzo', 'Docker', 'Kubernetes', 'Ansible'],
      live: true,
    },
    {
      id: 'cloudappi_2025',
      start: '2025-04', end: '2026-03',
      title:   { es: 'DevOps Manager',             en: 'DevOps Manager'             },
      company: 'CloudAppi',
      period:  { es: 'Abril 2025 — Marzo 2026',    en: 'April 2025 — March 2026'    },
      description: {
        es: 'Liderando un ejército de guerreros. En un entorno multi-nacional y multi-cliente, ofrecemos servicios de catálogo con las mejores tecnologías y metodologías para aportar valor real al negocio del cliente.',
        en: 'Leading an army of warriors. In a multi-national, multi-client environment, we deliver catalog services with the best technologies and methodologies to bring real value to our customers business.',
      },
      bullets: {
        es: [
          'Aplicar las mejores prácticas y metodologías DevOps/SRE',
          'Asegurar la satisfacción de nuestros clientes',
          'Reforzar al equipo en su proceso de crecimiento, mejora continua y optimización de procesos',
        ],
        en: [
          'Applying DevOps/SRE best practices and methodologies',
          "Ensuring our customers' satisfaction",
          'Empowering the team in their growth, continuous improvement, and process optimization',
        ],
      },
      stack: ['Azure', 'AWS', 'GCP', 'CI/CD', 'Kubernetes', 'Automation', 'App Architecture', 'SRE/DevOps'],
    },
    {
      id: 'ingram_sre_2022',
      start: '2022-01', end: '2025-04',
      title:   { es: 'Líder Técnico — Equipo Infraestructura/SRE', en: 'Infrastructure/SRE Technical Team Lead' },
      company: 'Ingram Micro Cloud',
      period:  { es: 'Enero 2022 — Abril 2025',    en: 'January 2022 — April 2025'  },
      description: {
        es: 'En una plataforma de 55B$ garantizamos Alta Disponibilidad, Escalabilidad y Observabilidad. Definimos estándares y procesos transversales; estamos inline en todos los pipelines CI/CD del producto asegurando compliance.',
        en: 'On a $55B platform we guarantee High Availability, Scalability and Observability. We define cross-team standards and processes; we sit inline in every product CI/CD pipeline ensuring compliance.',
      },
      bullets: {
        es: ['Garantizar Alta Disponibilidad', 'Garantizar Escalabilidad', 'Garantizar Observabilidad'],
        en: ['Guarantee High Availability',    'Guarantee Scalability',    'Guarantee Observability'],
      },
      stack: ['Azure', 'AWS', 'Automation', 'CI/CD', 'Kubernetes', 'Python', 'IaC', 'DataDog'],
    },
    {
      id: 'redhat_2021',
      start: '2021-07', end: '2022-01',
      title:   { es: 'Ingeniero de Soporte Senior — OpenShift', en: 'Senior Support Engineer — OpenShift' },
      company: 'Red Hat',
      period:  { es: 'Julio 2021 — Enero 2022',    en: 'July 2021 — January 2022'   },
      description: {
        es: 'Soporte avanzado de OpenShift sobre IBM Cloud Pak. Servicio nuevo, partnership con IBM, suite cloud potenciada con perks de IA.',
        en: 'Advanced OpenShift support on top of IBM Cloud Pak. Brand-new service in partnership with IBM, cloud suite boosted by AI perks.',
      },
      bullets: { es: [], en: [] },
      stack: ['Azure', 'OpenShift', 'RHEL', 'Docker', 'Kubernetes', 'IBM Cloud Pak', 'Hybrid Cloud'],
    },
    {
      id: 'ingram_cloud_2019',
      start: '2019-04', end: '2021-07',
      title:   { es: 'Administrador de Sistemas en la Nube', en: 'Cloud System Administrator' },
      company: 'Ingram Micro Cloud',
      period:  { es: 'Abril 2019 — Julio 2021',    en: 'April 2019 — July 2021'     },
      description: {
        es: 'Migración de Odin Automation (monolito on-prem global) a CloudBlue, un marketplace de 5B$ rediseñado como micro-servicios en Azure AKS.',
        en: 'Migration of Odin Automation (a worldwide on-prem monolith) to CloudBlue, a $5B marketplace re-designed as micro-services on Azure AKS.',
      },
      bullets: {
        es: [
          'Diseño de la nueva plataforma en Azure, AWS y GCP',
          'Rol de Arquitecto y Solution Architect alineando estrategia técnica y de negocio',
          'Soporte técnico de primer nivel',
        ],
        en: [
          'Designed the new platform across Azure, AWS and GCP',
          'Acted as Architect / Solution Architect aligning technical and business strategy',
          'Top-tier technical support',
        ],
      },
      stack: ['Azure', 'AWS', 'GCP', 'Linux', 'Docker', 'Kubernetes', 'PowerShell', 'VMware', 'Terraform', 'Puppet'],
    },
    {
      id: 'atos_2016',
      start: '2016-07', end: '2019-04',
      title:   { es: 'Team Leader — Redes y Seguridad Perimetral', en: 'Team Leader — Networking & Perimeter Security' },
      company: 'ATOS IT Solutions',
      period:  { es: 'Julio 2016 — Abril 2019',    en: 'July 2016 — April 2019'     },
      description: {
        es: 'Proyecto para el Gobierno de Cantabria que tuve el honor de liderar.',
        en: 'Project for the Cantabria Government I had the honor to lead.',
      },
      bullets: {
        es: [
          'Máxima autoridad en redes y seguridad perimetral',
          'Mantenimiento y diseño de la infraestructura de red',
          'Responsable de las comunicaciones con el cliente',
          'Supervisión del flujo de trabajo y cumplimiento de SLAs',
        ],
        en: [
          'Top-tier authority on networking and perimeter security',
          'Maintained and designed the networking infrastructure',
          "Owner of customer communications",
          "Monitored team workflow and SLA compliance",
        ],
      },
      stack: ['Cisco', 'Enterasys', 'Fortinet', 'Juniper', 'BigIP F5', 'IPS/IDS', 'WAF', 'Bluecoat', 'VMware'],
    },
    {
      id: 'ambar_2011',
      start: '2011-06', end: '2016-07',
      title:   { es: 'Team Leader — Jefe de Línea de Negocios Estratégicos', en: 'Team Leader — Head of Strategic Business Line' },
      company: 'Ambar Comunicaciones SL',
      period:  { es: 'Junio 2011 — Julio 2016',    en: 'June 2011 — July 2016'      },
      description: {
        es: 'Lideré dos equipos: Redes/Seguridad Perimetral y Housing. Renovación HW completa del contrato, migraciones de proveedor, gestión de servicios housing en datacenter propio.',
        en: 'Led two teams: Networking/Perimeter Security and Housing. Full HW renewal of the contract, vendor migrations, managed-services delivery from our own datacenter.',
      },
      bullets: {
        es: [
          'Mantenimiento de la infraestructura de red completa',
          'Servicios housing y managed-services en datacenter propio',
          'Comunicaciones con cliente y cumplimiento de SLAs',
        ],
        en: [
          'Owned the full networking infrastructure',
          'Housing and managed-services delivery from our datacenter',
          'Customer communications and SLA compliance',
        ],
      },
      stack: ['IPtables', 'Enterasys', 'Fortinet', 'Checkpoint', 'DNS', 'Apache', 'nginx', 'VMware', 'Juniper SA4500'],
    },
    {
      id: 'valnera_2008',
      start: '2008-01', end: '2011-06',
      title:   { es: '2º Nivel — Redes y Seguridad Perimetral', en: '2nd Tier — Networking & Perimeter Security' },
      company: 'Valnera Consultoría y Sistemas SL',
      period:  { es: 'Enero 2008 — Junio 2011',    en: 'January 2008 — June 2011'   },
      description: {
        es: 'Soporte de 2º nivel al Gobierno de Cantabria.',
        en: '2nd-tier support to the Cantabria Government.',
      },
      bullets: {
        es: [
          'Despliegue from-scratch de una solución de monitorización con Zabbix',
          'Gestión de servicios de Internet: DNS (bind), relés SMTP (postfix/sendmail), antispam (greylist + SpamAssassin + ClamAV + RBL)',
        ],
        en: [
          'Deployed a Zabbix monitoring solution from scratch',
          'Managed Internet services: DNS (bind), SMTP relays (postfix/sendmail), anti-spam (greylist + SpamAssassin + ClamAV + RBL)',
        ],
      },
      stack: ['IPtables', 'Cisco Pix', 'Sendmail', 'Bind', 'Zabbix', 'Red Hat', 'Contivity VPN'],
    },
    {
      id: 'ibm_2006',
      start: '2006-01', end: '2008-01',
      title:   { es: 'Operador de Host', en: 'Host Operator' },
      company: 'Ingeniería de Software Avanzado (IBM Global Services)',
      period:  { es: 'Enero 2006 — Enero 2008',    en: 'January 2006 — January 2008' },
      description: {
        es: 'Operador de Mainframe.',
        en: 'Mainframe Operator.',
      },
      bullets: {
        es: ['Coordinador de Equipo', 'Instructor de Linux'],
        en: ['Team Coordinator',     'Linux Trainer'],
      },
      stack: ['Mainframe', 'MVS', 'zOS', 'CONTROL-M', 'OPCC'],
    },
  ],

  certifications: [
    { year: 2021, name: 'Red Hat Certified System Administrator (RHCSA)',                       highlight: 'Red Hat' },
    { year: 2021, name: 'Red Hat Certified Specialist in Containers and Kubernetes (EX180)',    highlight: 'Containers and Kubernetes' },
    { year: 2015, name: 'Cisco CCNA Routing and Switching',                                     highlight: 'Cisco' },
    { year: 2015, name: 'Fortigate Certified Networking Security Professional FCNSP v5',        highlight: 'Fortigate' },
    { year: 2014, name: 'Fortigate Certified Network Security Administrator FCNSA v5',          highlight: null },
    { year: 2012, name: 'Enterasys Certified Specialist — Routing',                             highlight: 'Enterasys' },
    { year: 2012, name: 'Enterasys Certified Specialist — Switching',                           highlight: null },
    { year: 2012, name: 'Cisco Certified Entry Networking Technician (CCENT)',                  highlight: null },
    { year: 2010, name: 'ITIL Foundations V3',                                                  highlight: 'ITIL' },
    { year: 2008, name: 'ITIL Foundations V2',                                                  highlight: null },
  ],

  trainings: [
    { hours: 35, provider: 'Hewlett Packard',     name: { es: 'vSphere 4.1 — Instalación, Configuración y Gestión',  en: 'vSphere 4.1 — Installation, Configuration & Management' } },
    { hours: 35, provider: 'Hewlett Packard',     name: { es: 'HP Virtual Connect para HP BladeSystem',              en: 'HP Virtual Connect for HP BladeSystem' } },
    { hours: 35, provider: 'Enterasys',           name: { es: 'Enterasys Certified Specialist — NAC',                en: 'Enterasys Certified Specialist — NAC' } },
    { hours: 35, provider: 'Cisco Systems',       name: { es: 'Implementing Cisco MPLS',                             en: 'Implementing Cisco MPLS' } },
    { hours: 35, provider: 'NextiraONE',          name: { es: 'Alcatel OXE — Telefonía',                             en: 'Alcatel OXE — Telephony' } },
    { hours: 35, provider: 'Fortinet',            name: { es: 'Fortigate Multi-threat Security Systems I/II',        en: 'Fortigate Multi-threat Security Systems I/II' } },
    { hours: 35, provider: 'Hewlett Packard',     name: { es: 'Management & Monitoring — Insight Control',           en: 'Management & Monitoring — Insight Control' } },
  ],

  skills: {
    es: [
      { group: 'Cloud Platforms',  items: ['Azure', 'AWS', 'GCP'] },
      { group: 'DevOps & SRE',     items: ['Docker', 'Kubernetes', 'CI/CD', 'GitOps', 'Observabilidad'] },
      { group: 'Infrastructure',   items: ['Terraform', 'Ansible', 'Puppet', 'Linux', 'Networking', 'Security'] },
      { group: 'Leadership',       items: ['Gestión de equipos', 'Estrategia técnica', 'Stakeholder Comm'] },
    ],
    en: [
      { group: 'Cloud Platforms',  items: ['Azure', 'AWS', 'GCP'] },
      { group: 'DevOps & SRE',     items: ['Docker', 'Kubernetes', 'CI/CD', 'GitOps', 'Observability'] },
      { group: 'Infrastructure',   items: ['Terraform', 'Ansible', 'Puppet', 'Linux', 'Networking', 'Security'] },
      { group: 'Leadership',       items: ['Team Management', 'Technical Strategy', 'Stakeholder Comm'] },
    ],
  },

  /* Log lines for the now_playing.log panel (cycled). */
  log_lines: {
    es: [
      '[OK]  systemd: jose.gomez.service started',
      '[OK]  loading 20y of experience.db',
      '[INFO] cloud.providers ← azure, aws, gcp',
      '[OK]  k8s/clusters online (prod, stg, dev)',
      '[WARN] coffee.queue depth = 0 — refill required',
      '[INFO] ssh prod-eu-1 ✓',
      '[OK]  pipeline #4892 green',
      '[INFO] available for senior leadership',
      '[OK]  team.morale = high',
      '[INFO] commit a3f9c4 — refactor: extract orbital',
    ],
    en: [
      '[OK]  systemd: jose.gomez.service started',
      '[OK]  loading 20y of experience.db',
      '[INFO] cloud.providers ← azure, aws, gcp',
      '[OK]  k8s/clusters online (prod, stg, dev)',
      '[WARN] coffee.queue depth = 0 — refill required',
      '[INFO] ssh prod-eu-1 ✓',
      '[OK]  pipeline #4892 green',
      '[INFO] available for senior leadership',
      '[OK]  team.morale = high',
      '[INFO] commit a3f9c4 — refactor: extract orbital',
    ],
  },

  /* Telemetry counters shown in PANEL_02. Computed at runtime from the data above
     when possible; fallback constants live here. */
  telemetry: {
    es: [
      { label: 'YEARS',     key: 'years'     },
      { label: 'ROLES',     key: 'roles'     },
      { label: 'CERTS',     key: 'certs'     },
      { label: 'TRAININGS', key: 'trainings' },
      { label: 'COMPANIES', key: 'companies' },
      { label: 'CLOUDS',    key: 'clouds'    },
    ],
    en: [
      { label: 'YEARS',     key: 'years'     },
      { label: 'ROLES',     key: 'roles'     },
      { label: 'CERTS',     key: 'certs'     },
      { label: 'TRAININGS', key: 'trainings' },
      { label: 'COMPANIES', key: 'companies' },
      { label: 'CLOUDS',    key: 'clouds'    },
    ],
  },

  ui_labels: {
    es: {
      section_01: 'SECTION 01: system_monitor.live',
      panel_01:   'PANEL_01: career_timeline.tsv',
      panel_02:   'PANEL_02: telemetry.stream',
      panel_03:   'PANEL_03: stack_heatmap.matrix',
      panel_04:   'PANEL_04: neural.graph · jobs ↔ stack',
      panel_05:   'PANEL_05: now_playing.log',
      section_02: 'SECTION 02: experience.history',
      section_03: 'SECTION 03: active_integrations.orbital',
      section_04: 'SECTION 04: skills.matrix',
      section_05: 'SECTION 05: certifications.ledger',
      section_06: 'SECTION 06: trainings.archive',
      section_07: 'SECTION 07: languages.dial / other.modules',
      section_08: 'SECTION 08: subject.profile',
      section_09: 'SECTION 09: end_of_transmission',
      download_pdf: 'Descargar CV PDF',
      contact:      'Contactar',
      open_palette: 'Abrir paleta (⌘K)',
      static_on:    'STATIC',
      static_off:   'LIVE',
      tailing:      'TAILING',
      live_badge:   'LIVE',
      uptime:       'UPTIME',
      uid:          'UID',
      sys:          'SYS',
      languages_h:  'Idiomas',
      location_h:   'Ubicación',
      profile_h:    'Sobre mí',
      experience_h: 'Experiencia',
      certs_h:      'Certificaciones',
      trainings_h:  'Formación',
      contact_h:    'Contacto',
      konami_title: 'ACCESS GRANTED',
      konami_msg:   '// session.transferred · welcome to the team',
      static_hint:  '⌘K → toggle static',
      scroll_hint:  'scroll',
    },
    en: {
      section_01: 'SECTION 01: system_monitor.live',
      panel_01:   'PANEL_01: career_timeline.tsv',
      panel_02:   'PANEL_02: telemetry.stream',
      panel_03:   'PANEL_03: stack_heatmap.matrix',
      panel_04:   'PANEL_04: neural.graph · jobs ↔ stack',
      panel_05:   'PANEL_05: now_playing.log',
      section_02: 'SECTION 02: experience.history',
      section_03: 'SECTION 03: active_integrations.orbital',
      section_04: 'SECTION 04: skills.matrix',
      section_05: 'SECTION 05: certifications.ledger',
      section_06: 'SECTION 06: trainings.archive',
      section_07: 'SECTION 07: languages.dial / other.modules',
      section_08: 'SECTION 08: subject.profile',
      section_09: 'SECTION 09: end_of_transmission',
      download_pdf: 'Download CV PDF',
      contact:      'Contact',
      open_palette: 'Open palette (⌘K)',
      static_on:    'STATIC',
      static_off:   'LIVE',
      tailing:      'TAILING',
      live_badge:   'LIVE',
      uptime:       'UPTIME',
      uid:          'UID',
      sys:          'SYS',
      languages_h:  'Languages',
      location_h:   'Location',
      profile_h:    'About me',
      experience_h: 'Experience',
      certs_h:      'Certifications',
      trainings_h:  'Training',
      contact_h:    'Contact',
      konami_title: 'ACCESS GRANTED',
      konami_msg:   '// session.transferred · welcome to the team',
      static_hint:  '⌘K → toggle static',
      scroll_hint:  'scroll',
    },
  },
};
